"""Deterministic _index.md generation (spec 4.3)."""
import difflib
from pathlib import Path

HEADER = "<!-- generated by `sb index --write`; manual edits are overwritten -->\n\n"


def summary_of(note):
    text = " ".join(str(note.data.get("summary", "")).split())
    return text or "(no summary)"


def build(notes):
    ordered = sorted(notes, key=lambda n: (n.name.casefold(), n.name))
    return HEADER + "".join("- [[%s]]: %s\n" % (n.name, summary_of(n)) for n in ordered)


def drift(root, notes):
    """Unified diff between the current _index.md and the expected one; "" when in sync."""
    expected = build(notes)
    path = Path(root) / "_index.md"
    try:
        actual = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        actual = ""
    if actual == expected:
        return ""
    return "".join(difflib.unified_diff(actual.splitlines(True), expected.splitlines(True),
                                        "_index.md", "expected"))
